#!/bin/bash

##################################################################### 
# aws-instances      #   By: Don! Briggs <DonBriggsWork@gmail.com>  #
#####################################################################
# Return list of instances, public-ip, and run states for all
# instances, or for an instance whos name is passed
#

clear
aws ec2 describe-instances \
   --output json \
   --query "Reservations[*].Instances[*]"

    # --query "Reservations[*].Instances[*]" \
    # --output json



# aws ec2 describe-vpcs \
#   --query "Vpcs[*].[State]" \
#   --query "Reservations[*].Instances[*].[ImageId,InstanceType] " \

  # --filters "Name=tag:Name,Values=wgtmp-ubu" \
  # --query "Instances[*]" \

