#!/bin/bash
#####################################################################
#   instance   #   By: Don!Briggs   #       15-October-2023         #
#####################################################################
# List running instances in default AWS account                     #
#####################################################################

#  aws ec2 describe-instances --output=text --query "Reservations[*].Instances[].[KeyName,InstanceId,PublicDnsName]"
aws ec2 describe-instances --output=text --query "Reservations[*].Instances[].[PublicDnsName]"