#!/bin/bash

#
# inst_lamp      | By Don! Briggs <DonBriggsWork@gmail.com>
#
# Install, configure and verify LAMP stack on Ubuntu 22.xx or newer,
# with some intelligence. 

distro='ubuntu'     # Set name of Linux distrobution. (Initially only Ubuntu)
srvname='apache2'   # Package name for web server (apache, apache2, httpd, etc.)
dbname='mariadb'    # Package name for database server (mysql, mariadb, etc.)
phpname='php'       # Package name for PHP

#################  Function Block  ##################

function pause(){
    printf "\n"
    read -r -s -n 1 -p "    Press any key to continue . . ."
    echo ""
}
 
function pkgIsInstalled(){


    # Print error and exit if no param passed
    if [ -z $1 ]
    then
        printf "\ERROR: pkgIsInstalled - No Package Name passed\n\n"
        exit 250
    fi

    # Set global variable indicating if pasckage is installed
    if ! command -v $1 &> /dev/null
    then
        isInstalled=
        echo "$1 could not be found"
        # exit 1
    else
        isInstalled='true'
        echo "$1 LOCATED!!!"
    fi

}

function showBanner() {
    clear
    printf "\n"
    printf %90s |tr " " "=" 
    printf "\n                                 INSTALL LAMP STACK\n"
    printf %90s |tr " " "=" 
    printf "\n"
    printf "  This script will install and configure all components of the LAMP stack.\n"
    pause
}

#################  Main Block  ##################
showBanner

clear
printf "\n -- Installing Apache\n"
printf "_______________________________________________________\n\n"
# pkgIsInstalled $srvname
sudo apt install -y apache2 
sudo ufw allow 80/tcp 
sudo ufw allow 443/tcp
sudo systemctl start apache2
sudo systemctl enable apache2
clear
printf "\n -- Verify Apache Configuration\n"
printf "_______________________________________________________\n\n"
sudo systemctl status apache2
pause

clear
printf "\n -- Installing PHP\n"
printf "_______________________________________________________\n\n"
sudo apt install -y php
sudo apt install -y php-xml 
sudo apt install -y php-curl

clear
wwwpwrms
cat '<?php phpinfo(); ?>' > /var/www/html/phpinfo.php
pause
printf "\n -- Verify PHP Configuration\n"
printf "_______________________________________________________\n\n"
sudo php --version
pause


clear
printf "\n -- Installing MariaDB\n"
printf "_______________________________________________________\n\n"
sudo apt install -y mariadb-server
printf "\n -- Verify MariaDB Configuration\n"
printf "_______________________________________________________\n\n"
sudo systemctl status mariadb
pause

clear
printf "\n -- Secureing MySQL\n"
printf "_______________________________________________________\n\n"
sudo mysql_secure_installation

clear
printf "\n -- Configuring Laravel via Composer\n"
printf "_______________________________________________________\n\n"

composer create-project laravel/laravel dev