#!/bin/bash

# Install Don!s standard packages

clear
printf "  INSTALLING STANDARD PACKAGES\n"
printf "=============================================================\n"

sudo apt-get install -y curl unzip software-properties-common apt-transport-https wget
sudo apt-get install -y transmission  lsb-release ca-certificates vim dirmngr
sudo apt-get install -y xclip git-gui cdist grub-efi
sudo apt-get install -y fuse s3fs git exfatprogs
sudo apt-get install -y openjdk-8-jre  python3-pip  linode-cli
sudo apt-get install -y openssh-server openssh-client
sudo apt-get install -y gparted gpart gdisk gnome-disk-utility
sudo apt-get install -y build-essential gcc