#!/bin/bash

#inst_laravel    By: Don! Briggs  <DonBriggsWork@gmail.com>
#
# Install the Laravel Development Framework on a Ubuntu based Linux
# host. This script depends on the 'inst_lamp' script which will 
# install the LAMP stack.

