#!/bin/bash
clear
printf "Disabling ipV6\n"
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
#net.ipv6.conf.all.disable_ipv6 = 1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
#net.ipv6.conf.default.disable_ipv6 = 1
ip a