#!/bin/bash

cd ~/Downloads

# Update operating system
sudo apt-get update -y
# && sudo apt-get dist-upgrade -y && sudo apt-get autoremove

# Install Gnome tweak tool
 sudo apt install -y gnome-tweak-tool gnome-shell-extensions dconf-editor gnome-weather kupfer


# Enable minimize on click
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'

# Remove Thunderbird, as we don't use it
sudo apt remove -y --purge thunderbird

# Install some basic packages
sudo apt install -y htop curl

# Install restricted extras and codecs
sudo apt install -y ubuntu-restricted-extras
sudo apt install -y libavcodec-extra
sudo apt install -y libdvd-pkg
sudo dpkg-reconfigure libdvd-pkg

# Install additional package managers
sudo apt install -y synaptic flatpak gnome-software-plugin-flatpak

# Add Flatpack repository
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install Sublime text
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
deb https://download.sublimetext.com/ apt/stable/

# Add temp and power management
sudo apt install -y tlp tlp-rdw
sudo tlp start

# Install VLC Player
linuxtechi@Ubuntu-Rocks:~$ sudo apt-get install vlc -y

# Install Skype 
linuxtechi@Ubuntu-Rocks:~$ wget https://repo.skype.com/latest/skypeforlinux-64.deb
linuxtechi@Ubuntu-Rocks:~$ sudo dpkg -i skypeforlinux-64.deb
linuxtechi@Ubuntu-Rocks:~$ sudo apt-get install -fy

# Install Virtual Box
sudo apt install -y virtualbox

# Call script to install LAMP
source ~/scripts/inst_lamp

# Call script to set www directory permissions
source ~/scripts/www_perms
# Final cleanup
sudo apt autoremove -y
sudo apt autoclean -y
sudo apt clean -y
