#!/bin/bash

# 

# This script will create an ssh key, save it to the .ssh directory, a

keydir="$HOME/.ssh/"
keyname="common"

ssh-keygen -t rsa -C 'Description'
ssh sheena@192.168.1.2 "chmod 700 .ssh; chmod 640 .ssh/authorized_keys"