#!/bin/bash
##################################################################
#       net         #   By: Don! Briggs   #   04-April-2019      #
##################################################################
#    Initialize easytether client
##################################################################
sudo easytether-usb
sudo systemctl restart systemd-networkd

