#!/bin/bash

# - Update cache and backup current sources list before beginning
sudo apt update -y
sudo cp /etc/apt/sources.list /etc/apt/sourceslist_$(date +"%Y%m%dT%H%M").bak
sudo apt update -y
sudo apt upgrade

# - Install some basic Linux components
sudo apt-get install -y synaptic
sudo apt-get install -y gparted
sudo apr-get install -y gnome-disk-utility
sudo apt-get install -y git
sudo apt-get install -y vlc
sudo apt-get install -y wget
sudo apt-get install -y curl
#sudo apt-get install -y apt-offline apt-offline-gui
sudo apt-get install -y keychain
sudo apt-get install -y nautilus-dropbox
sudo apt-get install -y python3-pip
sudo apt-get install -y openjdk-11-jdk
sudo apt-get install -y synaptic
sudo apt-get install -y gparted
sudo apt-get install -y bleachbit
sudo apt-get install -y tasksel
#sudo apt-get install -y timeshift

# Sublime Text
# ==========================================================
sudo apt update
sudo apt install dirmngr gnupg apt-transport-https ca-certificates software-properties-common
curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"
sudo apt install sublime-text

#- Install Python 3.9
#- Install Net-Beans IDE


# Required commponents to build Realtek driver
# ==========================================================
sudo apt-get install -y dkms
sudo apt-get install -y build-essential
sudo apt-get install -y bc
sudo apt-get install -y libelf-dev
sudo apt-get install -y linux-headers-'uname -r'

# Download and install Chrome web browswe
#cd ~/Downloads
#wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#sudo apt install ./google-chrome-stable_current_amd64.deb

#sudo apt-get install -y ubuntu-restricted-extras
sudo apt-get install -y xubuntu-community-artwork
sudo apt-get install -y blackbird-gtk-theme
sudo apt-get install -y xubuntu-docs
sudo apt get install -y xubuntu-icon-themes
sudo apt-get install -y xubuntu-restricted-addons
#sudo apt-get install -y xubuntu-wallpapers xul-ext-firefox
 
 
 # Install Gnome tweak tool
sudo apt install -y gnome-tweak-tool gnome-shell-extensions dconf-editor gnome-weather kupfer


# Enable minimize on click
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
