#!/bin/bash
#
# remfs
# Connect to remote SSHFS servers

#!/bin/bash
#
#sshfs ec2-user@ec2-3-93-67-245.compute-1.amazonaws.com:/home/ec2-user ~/remote/ -o IdentityFile="$HOME/.ssh/kp-web01.pem"
sshfs ec2-user@ec2-3-93-67-245.compute-1.amazonaws.com:/var/www/ ~/remote/ -o IdentityFile="$HOME/.ssh/kp-web01.pem"
