#!/bin/bash

# remfs
# Mount a remote directory to the local filesystem over ssh.
#
# sshfs ubuntu@ec2-3-85-209-96.compute-1.amazonaws.com:/home/ubuntu ~/remote/ -o IdentityFile="$HOME/.ssh/$idFile"

uid='ubuntu'
pubDns='ec2-18-234-82-168.compute-1.amazonaws.com'
idFile='wgtmp.pem'

printf "Connecting Mounting RFS: %s\n" "$pubDns"
sshfs "$uid@$pubDns:/home/$uid" "$HOME/remote" \
      -o IdentityFile="$HOME/.ssh/$idFile"
