#!/bin/bash

#####################################################################
# rip_lamp                      ##         Initial Rev: 22-Nov-2023 #
# By: Don! Briggs <donbriggs@donbriggs.com>                         #                  
#####################################################################
#
# Remove all LAMP packages, settings, directories, etc from the
# system in a not very graceful manner. This is a temporary dev
# script intended to be used in the testing of LAMP scripts.
#


#################  Function Block  ##################

function pause(){
    printf "\n"
    read -r -s -n 1 -p "    Press any key to continue . . ."
    echo ""
}


#################  Main Block  ##################

clear
printf "                  Ripping out LAMP\n"
printf "============================================================\n\n"
pause

# Rip out Maria
sudo apt remove -y --purge maria*
sudo rm -rf /etc/mysql

# Rip out PHP
sudo apt remove -y --purge php*

# Rip out Apache2
sudo apt remove -y --purge apache*

# Rip misc stuff
sudo rm -rf /home/dbriggs/.cache
sudo rm -rf /usr/bin/mysql_secure-installation
sudo rm -rf /var/log/php*
sudo rm -rf /var/log apache*
sudo rm -rf /var/www
sudo apt autoremove -y

clear
printf " * Checking for survivors\n"
pause
sudo find / -name maria*
sudo find / -name mysql*
sudo find / -name apache*
sudo find / -name php*