#!/bin/bash

#
# upgrade-dist             | By Don! Briggs <DonBriggsWork@gmail.com>
#
# Upgrade distribution from 22.04 to 23.10. This script takes a
# while to run. You should reboot after running this script.
#

printf "\n"
printf "======================================================================\n"
printf "                  Upgrading Ubuntu to ver 23.10\n"
printf "======================================================================\n"

DEBIAN_FRONTEND=noninteractive
define -x DEBIAN_FRONTEND=noninteractive
sudo apt install update-manager-core -y
sudo sed -i 's/jammy/mantic/g' /etc/apt/sources.list
sudo apt update
sudo apt upgrade -y
sudo apt dist-upgrade -y
