#!/bin/bash

#  vpn		By: Don! Briggs		<DonBriggsWork@gmail.com>
#
#  Manage the Nord VPN. I it is not installed. This scrip will attempt to
#  easily manage Nord VPN installation and status.-
#
#
# Control VPN. Install if not installed

if ! nordvpn -v <nordvpn> &> /dev/null
then
    echo "<nordvpn> could not be found, attempting to inatall and configure."
    sh <(curl -sSf https://downloads.nordcdn.com/apps/linux/install.sh)
    
    exit
fi

clear
printf "  VPN Contol\n"
printf "=======================================\n"
# get current status of VPN connection
status=$(nordvpn status | cut -f 6 -d ' ')
printf "  - Status: $status\n"

if [[ "$status" == "Disconnected"* ]]; then
    printf "  - Bringing VPN up\n"
    nordvpn set technology nordlynx > /dev/null
    nordvpn set firewall enabled > /dev/null
    nordvpn set killswitch enabled > /dev/null
    nordvpn set notify enabled > /dev/null
    nordvpn set ipv6 disabled > /dev/null
    #nordvpn settings
    nordvpn connect
else
    printf "  - Bringing VPN down\n"
    #nordvpn set technology nordlynx > /dev/null
    #nordvpn set firewall enabled > /dev/null
    nordvpn set killswitch disabled > /dev/null
    #nordvpn set notify enabled > /dev/null
    #nordvpn set ipv6 disabled > /dev/null
    #nordvpn settings
    nordvpn disconnect
fi

    nordvpn status